# Generated by Django 3.1.7 on 2021-12-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=5, unique=True, verbose_name='状態名称')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disp_no', models.PositiveSmallIntegerField(verbose_name='表示順')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='詳細')),
                ('user_name', models.CharField(blank=True, max_length=20, verbose_name='担当者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.status')),
            ],
        ),
    ]
