# Generated by Django 3.1.7 on 2021-12-31 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20211231_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.status'),
        ),
    ]
